=== JanSutmoeller/HFTL-APP/Versand.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Versand (Bestellung*,Kunde*,Artikel*)>
<!ELEMENT Datum (#PCDATA)>
<!ELEMENT Preis (#PCDATA)>

<!ELEMENT Kunde (Name)>
<!ELEMENT Name (#PCDATA)>

<!ELEMENT Artikel (Name)>
<!ELEMENT Bestellposition (#PCDATA)>



<!ATTLIST Bestellung
		BestNr ID #REQUIRED
		Kunde IDREF #REQUIRED
>

<!ATTLIST Kunde
		KID ID #REQUIRED
>
<!ATTLIST Artikel
		AID ID #REQUIRED
>
<!ATTLIST Bestellposition
		ArtID IDREF #REQUIRED
>

<!ENTITY copyright "&#xA9;">

=== JanSutmoeller/HFTL-APP/Versand.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Versand SYSTEM "Versand.dtd">


<Versand>
<!-- Es gibt kann nur einen Kunden zu einer Bestellung geben  -->

	<Bestellung BestNr='NR123456' Kunde="K123">
		<Datum>01.01.2011</Datum>
		<Preis>213,12</Preis>
		<Bestellposition ArtID="A123789">12</Bestellposition>
		<!-- Artikelanzahl zeigt per IDREF auf einen "globalen" Artikel  -->		
	</Bestellung>
	
	<Bestellung BestNr='NR1234568' Kunde="K123">
		<Datum>01.01.2011</Datum>
		<Preis>213,12</Preis>
		<Bestellposition ArtID="A123789">12</Bestellposition>		
	</Bestellung>
	
	
	<Kunde KID="K123">
		<Name>Krause</Name>
	</Kunde>
	
	<Artikel AID="A123789">
		<Name>Laptop</Name>
	</Artikel>
	
	<Artikel AID="A1237812">
		<Name>Wurst</Name>
	</Artikel>

	<Artikel AID="A12378111">
		<Name>Kaese</Name>
	</Artikel>
	
	<Artikel AID="A178111">
		<Name>Kaese</Name>
	</Artikel>
	
	<Artikel AID="B7878111">
		<Name>Salami</Name>
	</Artikel>
	
	<Artikel AID="B78711">
		<Name>Marmelade</Name>
	</Artikel>


	<Artikel AID="B78w22711711">
		<Name>Gitarre</Name>
	</Artikel>

	<Artikel AID="Bowu01">
		<Name>Bockwurstsalat</Name>
	</Artikel>

	C:\Users\Student\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHu


</Versand>
